import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Script from 'next/script'
import './globals.css'
import { Suspense } from 'react'; // <--- Add this import

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'SelfPay Tool',
  description: 'Generated by Firebase Studio',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Google Analytics Scripts */}
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-04688HX4FP"
          strategy="afterInteractive"
        />
        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-04688HX4FP', {
              page_path: window.location.pathname,
            });

            if (window !== window.parent) {
              gtag('event', 'iframe_loaded', {
                event_category: 'Embed',
                event_label: document.referrer
              });
            }
          `}
        </Script>
        {/*<script src="https://js.stripe.com/v3/"></script> */}
        {/* Wrap the children with Suspense */}
        <Suspense fallback={<div>Loading...</div>}> {/* <--- Add opening Suspense tag */}
          {children}
        </Suspense> {/* <--- Add closing Suspense tag */}
      </body>
    </html>
  )
}